name = "your-cloudflare-project"
main = "./out-pages"
compatibility_date = "2025-10-16"

# Rellena `account_id` con tu Account ID de Cloudflare
account_id = "YOUR_ACCOUNT_ID"

[env.production]
name = "your-cloudflare-project-production"
 
# Tell Pages where the built output lives
pages_build_output_dir = "out-pages"

# Compatibility flags: keep empty to avoid unsupported flags like `nodejs_compat`.
compatibility_flags = []
